### PR TITLE
Add apparmor profile for ubuntu 16.04

### PR DESCRIPTION
**Pull request by petracvv**
### Description

This request adds an updated apparmor file for ubuntu 16.04 and preserves the 14.04 file if the cookbook runs on Ubuntu 14.04

### Issues Resolved

This is a slight re-implementation of Pull #547 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by damacus** [comment]
Would you mind doing one for 18.04 too please?

**Comment by petracvv** [comment]
I've added the 18.04 config (which is actually the same as the 16.04 config)

**Comment by petracvv** [comment]
Did you want it as a separate pull request? I didn't catch that initially

**Comment by damacus** [comment]
Nope, thats's great! 

Thank you.

**Pull request merged**
