### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mbaitelman**
Fix markdownlint issues

## Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/mysql/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by mbaitelman** [comment]
This fixes https://github.com/sous-chefs/mysql/runs/1191136314?check_suite_focus=true
https://github.com/sous-chefs/mysql/runs/1207358669?check_suite_focus=true

**Comment by ramereth** [comment]
@mbaitelman would you mind fixing the the `yamlint` warnings while you're at it too please?

**Comment by mbaitelman** [comment]
The yamllint is a little more complicated
The yaml does have `----` but the top of the file is ERB code. 
Il see if that's skippable

**Comment by mbaitelman** [comment]
It looks like yamllint supports a config but the actionshub/yamllint action doesn't support it (yet?)

**Comment by ramereth** [comment]
@mbaitelman PRs are welcome on actionshub to allow for configuration!

**Comment by mbaitelman** [comment]
Turns out there already is a system for default config files.
Replacing this PR with #649

**Pull request closed without merging**
