### PR TITLE
Add apparmor template for ubuntu 20.04

### PR DESCRIPTION
**Pull request by axos88**
Adds apparmor files for ubuntu 20.04. Simply copied the ubuntu 18.04 one.

### CODE REVIEW

**Comment by axos88** [comment]
Loosely related #654  #656

**Comment by axos88** [comment]
Failures seem unrelated: `        No candidate version available for mysql-community-server`

**Comment by ramereth** [comment]
> Failures seem unrelated: ` No candidate version available for mysql-community-server`

Indeed. It seems to be an upstream problem with the `mysql-cluster-8.0-community` repository.

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [10.0.1](https://github.com/sous-chefs/mysql/releases/tag/10.0.1)

**Pull request merged**
