### PR TITLE
Add mysql_user and mysql_database resources and remove Ubuntu 16.04 support

### LINKED ISSUE #522: Add mysql_database and mysql_database_user resources to this cookbook
As the database cookbook is meant to be deprecated, I'm requesting `mysql_database` and `mysql_database_user` be added to the mysql cookbook. This would help MySQL folks get off the database cookbook faster, which in turn would help database go to a farm upstate, where it can run and play and always be happy.

### PR DESCRIPTION
**Pull request by EMH333**
## Description

Adds `mysql_user` and `mysql_database` resources for creating, modifying and removing databases as well as database users. These resources were pulled from my https://github.com/sous-chefs/percona/pull/440 PR and modified to fit within this cookbook.

Edit: Also removes Ubuntu 16.04 support

### Issues Resolved

Fixes #522

### Check List
- [x] All tests pass. See https://github.com/sous-chefs/mysql/blob/master/TESTING.md
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by EMH333** [comment]
I'm unable to replicate the `resources-57-ubuntu-1604` test failure locally so I suspect it's just being flaky. I'll wait till I get a review to rerun tests/dive deeper if needed.

**Comment by ramereth** [comment]
@EMH333 any ideas why `resources-57-ubuntu-1604` is failing?

**Comment by ramereth** [comment]
@EMH333 I'm able to replicate it when using kitchen-dokken but not with using kitchen-vagrant.

**Comment by ramereth** [comment]
@EMH333 let's go ahead and remove Ubuntu 16.04 tests and see what we still need to fix to get this working. Looks like you still need to look into CentOS 8.

**Comment by EMH333** [comment]
Wait to merge, so I can fix the grant issue here as well (https://github.com/sous-chefs/percona/pull/445)

**Comment by EMH333** [comment]
I realized through the course of trying to find the converge error on Ubuntu 16.04 that the way this cookbook is set up and the way these resources work are fundamentally more different than I thought.

In the new resources, databases are selected via host/port or a socket for the default local server. Right now that doesn't match the way the rest of this cookbook is structured (multiple local db services, each with a different socket), and it might make sense to take the time to adapt it to that structure. The resources would have the option to take in the db service name, convert that to the proper socket file and use that instead of the conventional host/port or default socket. That logic is embedded within the resource, and it might take a lot of time to get right.

It wouldn't be a breaking change though, so we could just do a minor release later with that feature. And for people who just use a single database (named "default"), the current setup works perfectly fine.

Thoughts?

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [10.0.0](https://github.com/sous-chefs/mysql/releases/tag/10.0.0)

**Pull request merged**
