### PR TITLE
Actions fixes

### PR DESCRIPTION
**Pull request by mbaitelman**
## Description

Cleans up warnings in Actions
### Issues Resolved

N/A

### Check List
- [X] All tests pass. See https://github.com/sous-chefs/mysql/blob/master/TESTING.md
- [X] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by mbaitelman** [comment]
The .yamllint file is managed by repo-management. 
Depends on https://github.com/sous-chefs/repo-management/pull/47

**Comment by ramereth** [comment]
@mbaitelman I'm confused, this is change still needed?

**Comment by mbaitelman** [comment]
Yes, MDL was complaining about the lack of space around the header.

**Comment by ramereth** [comment]
Odd, I'm not triggering MDL complaining about `README.md` on the master branch.

**Comment by mbaitelman** [comment]
It was failing in https://github.com/sous-chefs/mysql/actions/runs/281555168

**Review by ramereth — APPROVED** [review]

**Pull request merged**
