### PR TITLE
Update 57 pw init

### PR DESCRIPTION
**Pull request by tealice**
## Description

* Adds and updates tests for 8.0 yum distros, I looked at adding 8.0 debian, but 8.0 was installing `mysql-systemd-start` script under `/usr/share/mysql/8.0` and didn't want to include too many changes here. 
* Modifies `v56plus` and `v57plus` methods to use `Gem::Version`
* Modify the `init_records_script` to set the root password using `ALTER USER` for 5.7+, from https://github.com/sous-chefs/mysql/pull/518 and the issue linked below. 

### Issues Resolved

Fixes https://github.com/sous-chefs/mysql/issues/410
closes #518 
### Check List
- [x] All tests pass. See https://github.com/sous-chefs/mysql/blob/master/TESTING.md
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable - 

Couple questions:

Should I update the README with which platforms have been tested with Test Kitchen? And not sure if I should add a DCO to any commits (maybe the vplus methods?) since the init_records_script modification was authored by someone else. Thanks!

### CODE REVIEW

**Comment by JohnRoesler** [comment]
@tealice would you fancy resolving the conflicts and working to get this merged in?

**Comment by Xorima** [comment]
Hey @tealice 

Any chance you could fix the issues with .kitchen so we can get tests passing etc?

Thanks!

**Comment by damacus** [comment]
Hey @tealice can you update your fork and fix the kitchen conflicts and we can ship this! 

Thanks,
Dan

**Comment by ramereth** [comment]
@tealice reping

**Comment by Xorima** [comment]
Closing due to inactivity. 

If this is still wanted please reopen or open another pull request. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Pull request closed without merging**
